alias ls='ls --color=auto'
alias i3config='vim ~/.config/i3/config'
alias update='yaourt -Syu'
alias remove='sudo pacman -R'
alias setup='yaourt -S'
alias orphans='sudo pacman -Rns $(pacman -Qtdq)'
alias paccache='paccache -k 3 -u -d'
alias pacclean='sudo pacman -Sc'
alias cpuinfo='cpupower frequency-info'
alias weather='curl wttr.in'
alias canopy='/home/mongwell/Canopy/canopy'
alias calculator='python3 /home/mongwell/Programming" "Workspace/Python/Python-Stackskills/Calculator/Calculator.py'
alias lock='~/.local/bin/distorted-pixelate-lock.sh'
alias gifbg="~/.local/bin/gifbg.sh"

