"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$os\
$memory_usage\
$jobs\
$sudo\
$cmd_duration \
$username\
$hostname\
$directory\
$package\
( $git_branch\
$git_commit\
$git_status\
$git_state)\
$line_break\
$character"""

right_format = """
$python\
$conda\
$rust\
$cmake\
$c\
$golang\
$java\
$julia\
$lua\
$ruby"""
#continuation_prompt

[c]
symbol = " "
detect_extensions = [ 'c', 'h', 'cpp', 'hpp' ]
commands = [[ 'clang', '--version' ], [ 'gcc', '--version' ], [ 'cc', '--version' ]]
version_format = 'v${major}'
style = 'bold blue'
format = '\[[$symbol(($name )$version)]($style)\]'

[character]
success_symbol = '[ ➜](bold bright-green) '
error_symbol = '[ ➜](bold red) '

[cmake]
version_format = 'v${major}.${minor}'
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
min_time = 5_000
format = '\[[⏱ $duration]($style)\]'

[conda]
symbol = " "
format = '\[[$symbol$environment]($style)\]'

[directory]
truncation_length = 2
format = '[$path]($style)[$read_only]($read_only_style)'
read_only = " "

[git_branch]
symbol = " "
style = 'bold dimmed green'
format = '\[[$symbol$branch]($style)\]'

[git_commit]
format = '\([$hash$tag]($style)\)'

[git_state]
format = '\[[$state( $progress_current/$progress_total)]($style)\]'

[git_status]
style = 'bold yellow'
untracked = 'u$count'
modified = '$count'
staged = '+$count'
format = '([\[$conflicted$staged$modified$untracked$ahead_behind\]]($style))'

[golang]
symbol = " "
version_format = "v${major}.$minor"
format = '\[[$symbol($version)]($style)\]'

[hostname]
format = '\[[$ssh_symbol$hostname]($style)\]'

[java]
symbol = " "
version_format = "v${major}.$minor"
format = '\[[$symbol($version)]($style)\]'

[jobs]
format = '\[[$symbol$number]($style)\]'

[julia]
symbol = " "
version_format = "v${major}.$minor"
format = '\[[$symbol($version)]($style)\]'

[line_break]
disabled = true

[lua]
symbol = " "
version_format = "v${major}.$minor"
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
symbol = " "
format = '\[$symbol[$ram_pct( | $swap_pct)]($style)\]'
disabled = false

[os]
disabled = false
format = '[$symbol]($style)'

[os.symbols]
Alpine = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Solus = "ﴱ "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[python]
symbol = " "
version_format = 'v${major}.${minor}'
style = 'bold bright-yellow'
format = '\[[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style)\]'

[ruby]
symbol = " "
version_format = 'v${major}.${minor}'
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = " "
version_format = 'v${major}.${minor}'
format = '\[[$symbol($version)]($style)\]'

[sudo]
disabled = false
symbol = '#'
format = '\[[$symbol]($style)\]'

[username]
format = '[$user]($style) '
